FROM postgres

COPY ./db_scripts/ /docker-entrypoint-initdb.d/

EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
# VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

CMD ["postgres"]
