version: "3.7"

services:
  db:
    container_name: my_db
    build:
      context: .
      dockerfile: ./Dockerfile-postgresql
    restart: always
    environment:
      POSTGRES_DB: nicoledb
      POSTGRES_USER: isdance
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4:4.25
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  pgadmin-data: